KeedoApp/Models/Consultation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace KeedoApp.Models
{

	public class Consultation
	{
		public int idConsultation { get; set; }
		[DataType(DataType.Date)]
		public DateTime dateConsultation { get; set; }
		[DataType(DataType.Time)]
		public DateTime time { get; set; }

		public int? directorFk { get; set; }
		public User director { get; set; }

		public int? doctorFk { get; set; }
		public User doctor { get; set; }

		public int? kidFk { get; set; }
		public Kid kid { get; set; }

	}
}

KeedoApp/Controllers/ConsultationController.cs
using KeedoApp.Extensions;
using KeedoApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KeedoApp.Controllers
{
    public class ConsultationController : Controller
    {

        // GET: Consultation
        public ActionResult Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8080/SpringMVC/servlet/");

            var _AccessToken = Session["AccessToken"];
            client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage httpResponseMessage = client.GetAsync("consult/getAll").Result;

            IEnumerable<Consultation> consultations;
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                consultations = httpResponseMessage.Content.ReadAsAsync<IEnumerable<Consultation>>().Result;

            }
            else
            {
                consultations = null;
            }
            return View(consultations);
        }

        // GET: Consultation/Details/5
        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8080/SpringMVC/servlet/");

            var _AccessToken = Session["AccessToken"];
            client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage httpResponseMessage = client.GetAsync("consult/get/" + id).Result;

            Consultation consult;
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                consult = httpResponseMessage.Content.ReadAsAsync<Consultation>().Result;
            }
            else
            {
                consult = null;
            }
            return View(consult);
        }

        // GET: Consultation/Create
        public ActionResult Create()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8080/SpringMVC/servlet/");

            var _AccessToken = Session["AccessToken"];
            client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage httpResponseMessage = client.GetAsync("kid/getAll").Result;
            HttpResponseMessage httpResponseMessage2 = client.GetAsync("consult/getDoctors").Result;
            IEnumerable<User> doctors;
            IEnumerable<Kid> kids;
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                kids = httpResponseMessage.Content.ReadAsAsync<IEnumerable<Kid>>().Result;
            }
            else
            {
                kids = null;
            }
            if (httpResponseMessage2.IsSuccessStatusCode)
            {
                doctors = httpResponseMessage2.Content.ReadAsAsync<IEnumerable<User>>().Result;
            }
            else
            {
                doctors = null;
            }
            ViewBag.kidFk = new SelectList(kids, "idKid", "FirstNameLastName");
            ViewBag.doctorFk = new SelectList(doctors, "idUser", "ReturnFirstLast");

            return View();
        }

        // POST: Consultation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Consultation consultation)
        {

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8080");

            var _AccessToken = Session["AccessToken"];
            client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var response = await client.PostAsJsonAsync("SpringMVC/servlet/consult/add/" + consultation.kidFk + "/" + consultation.doctorFk, consultation);
            if (response.IsSuccessStatusCode)
            {
                if (response.Content.ReadAsStringAsync().Result.ToString().Equals("1"))
                {
                    this.AddNotification("Wrong date !!", NotificationType.WARNING);
                }
                else if (response.Content.ReadAsStringAsync().Result.ToString().Equals("2"))
                {
                    this.AddNotification("Consultation added successfully !", NotificationType.SUCCESS);
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification("Doctor not available for this date !!", NotificationType.WARNING);
                }

            }

            //--------

            HttpResponseMessage httpResponseMessage = client.GetAsync("SpringMVC/servlet/kid/getAll").Result;
            HttpResponseMessage httpResponseMessage2 = client.GetAsync("SpringMVC/servlet/consult/getDoctors").Result;
            IEnumerable<User> doctors;
            IEnumerable<Kid> kids;
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                kids = httpResponseMessage.Content.ReadAsAsync<IEnumerable<Kid>>().Result;
            }
            else
            {
                kids = null;
            }
            if (httpResponseMessage2.IsSuccessStatusCode)
            {
                doctors = httpResponseMessage2.Content.ReadAsAsync<IEnumerable<User>>().Result;
            }
            else
            {
                doctors = null;
            }
            ViewBag.kidFk = new SelectList(kids, "idKid", "FirstNameLastName");
            ViewBag.doctorFk = new SelectList(doctors, "idUser", "ReturnFirstLast");

            return View(consultation);
        }


        // GET: Consultation/Edit/5
        public ActionResult Edit(int id)
        {
            Consultation consult = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8080/SpringMVC/servlet/");

                var _AccessToken = Session["AccessToken"];
                client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

                //HTTP GET
                var responseTask = client.GetAsync("consult/get/" + id);
                // responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<Consultation>();
                    readTask.Wait();

                    consult = readTask.Result;
                }
                //------------
                HttpResponseMessage httpResponseMessage = client.GetAsync("kid/getAll").Result;
                HttpResponseMessage httpResponseMessage2 = client.GetAsync("consult/getDoctors").Result;
                IEnumerable<User> doctors;
                IEnumerable<Kid> kids;
                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    kids = httpResponseMessage.Content.ReadAsAsync<IEnumerable<Kid>>().Result;
                }
                else
                {
                    kids = null;
                }
                if (httpResponseMessage2.IsSuccessStatusCode)
                {
                    doctors = httpResponseMessage2.Content.ReadAsAsync<IEnumerable<User>>().Result;
                }
                else
                {
                    doctors = null;
                }
                ViewBag.kidFk = new SelectList(kids, "idKid", "FirstNameLastName");
                ViewBag.doctorFk = new SelectList(doctors, "idUser", "ReturnFirstLast");

            }
            return View(consult);
        }

        // POST: Consultation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Consultation consult)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8080/SpringMVC/servlet/");

                var _AccessToken = Session["AccessToken"];
                client.DefaultRequestHeaders.Add("Authorization", String.Format("Bearer " + _AccessToken));

                //HTTP POST
                var putTask = client.PutAsJsonAsync<Consultation>("consult/up/" + id, consult);
                putTask.Wait();

                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    this.AddNotification("Consultation updated successfully !", NotificationType.SUCCESS);
                    return RedirectToAction("Index");
                }
                //------------
                HttpResponseMessage httpResponseMessage = client.GetAsync("kid/getAll").Result;
                HttpResponseMessage httpResponseMessage2 = client.GetAsync("consult/getDoctors").Result;
                IEnumerable<User> doctors;
                IEnumerable<Kid> kids;
                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    kids = httpResponseMessage.Content.ReadAsAsync<IEnumerable<Kid>>().Result;
                }
                else
                {
                    kids = null;
                }
                if (httpResponseMessage2.IsSuccessStatusCode)
                {
                    doctors = httpResponseMessage2.Content.ReadAsAsync<IEnumerable<User>>().Result;
                }
                else
                {

KeedoApp/Views/Consultation/Create.cshtml
@model KeedoApp.Models.Consultation

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Consultation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.dateConsultation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dateConsultation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dateConsultation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.doctor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.doctorFk, null, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.doctorFk, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.kid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.kidFk, null, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.kidFk, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <div>
        @Html.Partial("_Notifications")
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KeedoApp/Views/Consultation/Delete.cshtml
@model KeedoApp.Models.Consultation

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consultation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Date consultation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateConsultation)
        </dd>

        <dt>
           time
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            Created by
        </dt>

        <dd>
            @Html.DisplayFor(model => model.director.ReturnFirstLast)
        </dd>

        <dt>
            Doctor
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.ReturnFirstLast)
        </dd>

        <dt>
            Kid
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kid.FirstNameLastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KeedoApp/Views/Consultation/Details.cshtml
@model KeedoApp.Models.Consultation

<div>
    <h4>Consultation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Date consultation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateConsultation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            Created by
        </dt>

        <dd>
            @Html.DisplayFor(model => model.director.ReturnFirstLast)
        </dd>

        <dt>
            Doctor
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.ReturnFirstLast)
        </dd>

        <dt>
            Kid
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kid.FirstNameLastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idConsultation }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KeedoApp/Views/Consultation/Edit.cshtml
@model KeedoApp.Models.Consultation

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consultation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.dateConsultation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateConsultation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateConsultation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Doctor
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.doctorFk, null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doctorFk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kidFk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.kidFk, null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kidFk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KeedoApp/Views/Consultation/Index.cshtml
@model IEnumerable<KeedoApp.Models.Consultation>

<p>
    @Html.ActionLink("Create New", "Create")

</p>
<div>
    @Html.Partial("_Notifications")
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.dateConsultation)
            <a href="@Url.Action("ToDay","Consultation")"><img src="https://img.icons8.com/color/48/000000/tear-off-calendar--v2.png" /></a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th>
            Created by
        </th>
        <th>
            Doctor
        </th>
        <th>
            Kid
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dateConsultation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.director.ReturnFirstLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctor.ReturnFirstLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kid.FirstNameLastName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idConsultation }) |
                @Html.ActionLink("Details", "Details", new { id = item.idConsultation }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.idConsultation })
            </td>
        </tr>
    }

</table>

KeedoApp/Views/Consultation/ToDay.cshtml
@model IEnumerable<KeedoApp.Models.Consultation>

<p>
    @Html.ActionLink("Create New", "Create")

</p>
<div>
    @Html.Partial("_Notifications")
</div>
@ViewBag.message
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.dateConsultation)
            <a href="@Url.Action("ToDay","Consultation")"><img src="https://img.icons8.com/color/48/000000/tear-off-calendar--v2.png" /></a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th>
            Created by
        </th>
        <th>
            Doctor
        </th>
        <th>
            Kid
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dateConsultation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.director.ReturnFirstLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctor.ReturnFirstLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kid.FirstNameLastName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idConsultation }) |
                @Html.ActionLink("Details", "Details", new { id = item.idConsultation }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.idConsultation })
            </td>
        </tr>
    }

</table>